googleAnalytics = "G-FL0RFP3MP3"
baseURL = 'https://scheuclu.github.io'
languageCode = 'en-us'
title = 'Lukas Scheucher'
theme = "ananke"
enableEmoji = true
disqusShortname =  'lukasscheucher'
[markup.goldmark.renderer]
 unsafe = true
[sitemap]
 changefreq = "weekly"
 filename = "sitemap.xml"
 priority = 0.5
